# Generated by Django 6.0.2 on 2026-03-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.CharField(db_column='id', help_text='Module code. Check UofG course content page: https://www.gla.ac.uk/coursecatalogue/.', max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='Module name', max_length=255, unique=True)),
                ('level', models.PositiveIntegerField(db_column='level', help_text='Module level 1-5')),
                ('credits', models.PositiveIntegerField(db_column='credits', help_text='Module credits')),
                ('is_archived', models.BooleanField(db_column='is_archived', default=False, help_text='If true, model is archived and not shown unless filtered for. Does not accept new study materials.be')),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='modules.school')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('code', models.CharField(db_column='id', help_text='Degree code. Check UofG: https://www.gla.ac.uk/undergraduate/', max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='Full degree name.', max_length=255, unique=True)),
                ('degree_type', models.CharField(blank=True, choices=[('BSc', 'Bachelor of Science'), ('MSci', 'Master in Science'), ('MA', 'Master of Arts'), ('MA(SocSci)', 'Master of Arts (Social Sciences)'), ('BEng', 'Bachelor of Engineering'), ('MEng', 'Master of Engineering'), ('LLB', 'Bachelor of Laws'), ('BAcc', 'Bachelor of Accountancy'), ('BFin', 'Bachelor of Finance'), ('MBChB', 'Bachelor of Medicine, Bachelor of Surgery'), ('BDS', 'Bachelor of Dental Surgery'), ('BVMS', 'Bachelor of Veterinary Medicine & Surgery'), ('BN', 'Bachelor of Nursing'), ('BMus', 'Bachelor of Music'), ('MEduc', 'Master of Education'), ('MDTechEd', 'Master of Design & Technology Education'), ('BD', 'Bachelor of Divinity'), ('BA', 'Bachelor of Arts'), ('CertHE', 'Certificate of Higher Education'), ('LSc', 'Laurea in Statistica')], db_column='degree_type', help_text='Degree type (can be null due to some dual international degrees)', max_length=15, null=True)),
                ('schools', models.ManyToManyField(db_table='degree_school', related_name='degrees', to='modules.school')),
            ],
            options={
                'verbose_name': 'Degree Program',
                'verbose_name_plural': 'Degree Programs',
                'db_table': 'degree',
            },
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden_by_student', models.BooleanField(db_column='is_archived', default=False, help_text='Student can archive modules to hide them without unsubscribing')),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Module Subscription',
                'verbose_name_plural': 'Student Module Subscriptions',
                'db_table': 'student_module',
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.AddField(
            model_name='module',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_modules', through='modules.StudentModule', to='accounts.student'),
        ),
        migrations.CreateModel(
            name='PinnedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Pinned Module',
                'verbose_name_plural': 'Pinned Modules',
                'db_table': 'pinned_module',
                'unique_together': {('student', 'module')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('name', 'school')},
        ),
    ]
