# Generated by Django 6.0.3 on 2026-03-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(blank=True, db_column='degree_type', help_text='Degree type', max_length=31, null=True),
        ),
    ]
