# Generated by Django 6.0.3 on 2026-03-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_degree_degree_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(db_column='name', help_text='Full degree name.', max_length=255),
        ),
    ]
