# Generated by Django 6.0.3 on 2026-03-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_degree_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(db_column='name', help_text='Module name', max_length=255),
        ),
    ]
