# Generated by Django 6.0.3 on 2026-03-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_module_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('id', 'school')},
        ),
    ]
