# Generated by Django 6.0.2 on 2026-03-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', help_text='Name of the flashcard set or quiz', max_length=255)),
                ('material_type', models.CharField(choices=[('flashcard', 'Flashcard'), ('quiz', 'Quiz')], db_column='material_type', help_text='Type of study material', max_length=20)),
                ('is_published', models.BooleanField(db_column='is_published', default=False, help_text='If True, material is visible to all users in the module')),
                ('is_deleted', models.BooleanField(db_column='is_deleted', default=False, help_text='Soft delete - material marked as deleted but not removed from DB')),
                ('is_hidden_by_admin', models.BooleanField(db_column='is_hidden_by_admin', default=False, help_text='Admin has hidden this material due to inappropriate content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('module', models.ForeignKey(blank=True, db_column='module_id', help_text='Module this material belongs to. NULL means private/unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='modules.module')),
                ('owner', models.ForeignKey(db_column='owner_id', help_text='Student who created this material', on_delete=django.db.models.deletion.CASCADE, related_name='created_materials', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Study Material',
                'verbose_name_plural': 'Study Materials',
                'db_table': 'study_material',
            },
        ),
        migrations.CreateModel(
            name='PinnedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Pinned Material',
                'verbose_name_plural': 'Pinned Materials',
                'db_table': 'pinned_material',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(db_column='question_text', help_text='Question text - Markdown supported', max_length=1000)),
                ('question_type', models.CharField(choices=[('single', 'Single Answer - Pick One'), ('multiple', 'Multiple Answers - Select All That Apply')], db_column='question_type', default='single', help_text='Single answer (radio buttons) or multiple answers (checkboxes)', max_length=10)),
                ('order', models.IntegerField(db_column='order', help_text='Display order of questions')),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'db_table': 'quiz_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('study_material', models.OneToOneField(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flashcard_set', serialize=False, to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Flashcard Set',
                'verbose_name_plural': 'Flashcard Sets',
                'db_table': 'flashcard_set',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('study_material', models.OneToOneField(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz', serialize=False, to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quiz',
            },
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='pinned_by',
            field=models.ManyToManyField(help_text='Students who starred this material for quick access', related_name='pinned_material', through='materials.PinnedMaterial', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='pinnedmaterial',
            name='study_material',
            field=models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, to='materials.studymaterial'),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(db_column='answer_text', help_text='Answer text - Markdown supported', max_length=500)),
                ('is_correct', models.BooleanField(db_column='is_correct', default=False, help_text='True if this is a correct answer')),
                ('order', models.IntegerField(db_column='order', help_text='Display order of answers')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='materials.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'db_table': 'quiz_answer',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('spam', 'Spam'), ('incorrect', 'Incorrect Information'), ('offensive', 'Offensive/Harassment'), ('other', 'Other')], db_column='reason', max_length=20)),
                ('details', models.TextField(blank=True, db_column='details', help_text='Additional details about the report', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('is_reviewed', models.BooleanField(db_column='is_reviewed', default=False, help_text='Has an admin reviewed this report?')),
                ('reporter', models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='accounts.student')),
                ('study_material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('study_material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Upvote',
                'verbose_name_plural': 'Upvotes',
                'db_table': 'upvote',
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(db_column='front', help_text='Front of card (question/term) - Markdown supported', max_length=500)),
                ('back', models.TextField(db_column='back', help_text='Back of card (answer/definition) - Markdown supported', max_length=1000)),
                ('order', models.IntegerField(db_column='order', help_text='Display order in the set')),
                ('flashcard_set', models.ForeignKey(db_column='set_id', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='materials.flashcardset')),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'db_table': 'flashcard',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='materials.quiz'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='content', help_text='Content of comment (Max 3000 characters)', max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.student')),
                ('study_material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['study_material'], name='idx_comment_material')],
            },
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['owner'], name='idx_material_owner'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['module', 'is_published', 'is_deleted', 'is_hidden_by_admin'], name='idx_material_module_pub'),
        ),
        migrations.AlterUniqueTogether(
            name='pinnedmaterial',
            unique_together={('student', 'study_material')},
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'study_material')},
        ),
        migrations.AddIndex(
            model_name='upvote',
            index=models.Index(fields=['study_material'], name='idx_upvote_material'),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('student', 'study_material')},
        ),
    ]
