# Generated by Django 6.0.3 on 2026-03-27 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_column='is_deleted', default=False, help_text='Soft delete, hidden from students but visible to moderators'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='materials.comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='study_material',
            field=models.ForeignKey(blank=True, db_column='material_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='materials.studymaterial'),
        ),
    ]
