# Generated by Django 6.0.3 on 2026-03-27 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_is_staff_and_more'),
        ('materials', '0002_alter_report_unique_together_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_materials_assoc', to='accounts.student')),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_students', to='materials.studymaterial')),
            ],
            options={
                'verbose_name': 'Saved Material',
                'verbose_name_plural': 'Saved Materials',
                'db_table': 'saved_material',
                'unique_together': {('student', 'study_material')},
            },
        ),
    ]
