# Generated by Django 6.0.2 on 2026-03-03 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(db_column='degree_id', on_delete=django.db.models.deletion.PROTECT, to='modules.degree'),
        ),
    ]
